ToDoApp/ToDoApp/Models/Aircraft.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToDoApp.Models
{
    public enum Roles { Fighter, Bomber, Multirole, Recconainsense, Trainer, Transport }
    public class Aircraft
    {
        [Key]
        public int Id { get; set; }
        [Required] public string Type { get; set; } 
        [EnumDataType(typeof(Roles))] public Roles Role { get; set; }
        public int Crew { get; set; }
        public int Range { get; set; }
        public int Speed { get; set; }
        public int Load { get; set; }
        public bool Stealth { get; set; }
     }
}

ToDoApp/ToDoApp/Controllers/AircraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{
    public class AircraftController : Controller
    {
        DbAircraft dbAircaft = new DbAircraft();
        
        // GET: Aircraft
        public ActionResult Index()
        { 
            return View(dbAircaft.AirCrafts.ToList());
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string type, Roles role, int crew, int range, int speed, int load, bool stealth)
        {
            if (!string.IsNullOrEmpty(type))
            {
                dbAircaft.AirCrafts.Add(new Aircraft { Type = type, Role = role, Crew = crew, Range = range, Speed = speed, Load = load, Stealth = stealth });

                dbAircaft.SaveChanges();
                return RedirectToAction("Index");
            }
                return View();            
        }

        public ActionResult Details(int id)
        {
            var item = dbAircaft.AirCrafts.Single(x => x.Id == id);
            return View(item);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var item = dbAircaft.AirCrafts.Single(x => x.Id == id);
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(int id, string type, Roles role, int crew, int range, int speed, int load, bool stealth)
        {
            var item = dbAircaft.AirCrafts.Single(x => x.Id == id);
            item.Type = type;
            item.Role = role;
            item.Crew = crew;
            item.Range = range;
            item.Speed = speed;
            item.Load = load;
            item.Stealth = stealth;

            dbAircaft.SaveChanges();
            return RedirectToAction("Index");            
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var item = dbAircaft.AirCrafts.Single(x => x.Id == id);
            return View(item);
        }

        public ActionResult DeleteConfirmed(int id)
        {
            var item = dbAircaft.AirCrafts.Single(x => x.Id == id);
            dbAircaft.AirCrafts.Remove(item);
            dbAircaft.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

ToDoApp/ToDoApp/Views/Aircraft/Create.cshtml
@{
    ViewBag.Title = "Create";
}

@*@using MyMVCApp.Models*@
@model List<ToDoApp.Models.Aircraft>

<h2>Create a new entry</h2>

<form method="post">
    <label>Type </label> <input name="Type">
    @*<br><label>Role </label> <input name="Role" />*@
    <br/>@Html.DropDownList("Role",
                    new SelectList(Enum.GetValues(typeof(ToDoApp.Models.Roles))),
                    "Select Role",
                    new { @class = "form-control" })
    <br><label>Crew number</label> <input name="Crew" />
    <br><label>Range [km]</label> <input name="Range" />
    <br><label>Max Speed [km/h]</label> <input name="Speed" />
    <br><label>Max load [kg]</label> <input name="Load" />
    <br><label>Stealth</label> <input id="Stealth" name="Stealth" type="checkbox" value="true" />
    <input name="Stealth" type="hidden" value="false" />
    <br>
    <button>Save</button>

</form>

@Html.ActionLink("Cancel", "Index")

ToDoApp/ToDoApp/Views/Aircraft/Delete.cshtml
@model ToDoApp.Models.Aircraft

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aircraft</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Crew)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Crew)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Range)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Range)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Load)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Load)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stealth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stealth)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Aircraft"))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoApp/ToDoApp/Views/Aircraft/Details.cshtml
@model ToDoApp.Models.Aircraft

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Aircraft</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Role)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Role)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Crew)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Crew)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Range)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Range)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Speed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Speed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Load)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Load)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stealth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stealth)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoApp/ToDoApp/Views/Aircraft/Edit.cshtml
@model ToDoApp.Models.Aircraft
@{
    /**/

    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Aircraft", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)

    <label>Type            </label> @Html.EditorFor(x => x.Type)
    <br><label>Role            </label>@Html.DropDownList("Role",
            new SelectList(Enum.GetValues(typeof(ToDoApp.Models.Roles))),
            "Select Role",
            new { @class = "form-control" })    
    <br><label>Crew number     </label>@Html.EditorFor(x => x.Crew)
    <br><label>Range [km]      </label>@Html.EditorFor(x => x.Range)
    <br><label>Max Speed [km/h]</label>@Html.EditorFor(x => x.Speed)
    <br><label>Max load [kg]   </label>@Html.EditorFor(x => x.Load)
    <br><label>Stealth         </label>@Html.EditorFor(x => x.Stealth)

    <input type="submit" value="Mentés" />
}

@Html.ActionLink("Back to List", "Index")

ToDoApp/ToDoApp/Views/Aircraft/Index.cshtml
@model List<ToDoApp.Models.Aircraft>

@{
    ViewBag.Title = "Index";
}

<h2>Index page. Lists all items in the database.</h2>

<ol>
    @foreach (var plane in Model)
    {
        @*<li>@Html.DisplayText(plane.Type)</li>*@ @*nem mukodik*@        
    <li>@Html.ActionLink(plane.Type, "Details", new { id = plane.Id })  @Html.ActionLink("Edit", "Edit", new { id = plane.Id })  @Html.ActionLink("Delete", "Delete", new { id = plane.Id })  </li>
    }

</ol>

<li>@Html.ActionLink("Add Plane","Create")</li>