ToDoApp/ToDoApp/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToDoApp.Models;

namespace ToDoApp.Controllers
{    
    public class TodoController : Controller
    {
        Db db = new Db();
        public ActionResult Index()
        {
            return View(db.TodoItems.ToList()); //Az index oldalunk nem dbSet tipust, hanem listat var
        }

        //[HttpGet, HttpPost]
        [HttpGet] //annotacio. A routing innentol csak a GET keresek eseten iranyit ide
        public ActionResult Create()  //lekerjuk az urlapot
        {
            return View();
        }

        [HttpPost]//annotacio. A routing innentol csak a POST keresek eseten iranyit ide
        public ActionResult Create(string name, bool isDone)
        {
            if (!string.IsNullOrEmpty(name))
            {//Ha van adat a parameterben
                //adatok mentese es vissza az indexre
                //Ez nem jo, mert ha torlok a listabol, akkor onnantol ez duplazni fogja az Id-kat
                //var maxId = MyDb.Lista.Count;

                //var maxId = MyDb.Lista.Max(x => x.Id);
                //MyDb.Lista.Add(new TodoItem() { Id = maxId+1, Name = name, Done = isDone });
                db.TodoItems.Add (new TodoItem() { Name = name, Done = isDone }); //a kulcs mezot az adatb automatikusan kezeli
                //adatbazisba irni:
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //todo: mivel a adat nem valid, itt kene a hibauzenettel valamit kezdeni
            //(kiadni az ugyfel fele)
            return View();
        }

        /// <summary>
        /// Az action feladata az adott elem megjelenitese modositasra.
        /// Azomositas ID alapjan.
        /// </summary>
        /// <param name="id">a modositando tetel azonositoja</param>
        /// <returns></returns>
        [HttpGet] //lekerjuk az urlapot
        public ActionResult Edit(int id)
        {
            //elo kell keresni az adott elemet
            //MyDb.Lista.Where(x=>x.Id == id); //Olyan lista lesz, amin csak az id-nak megfelelo elemek vannak, azaz 1 db.
            
            //csak, ha garantalni tudom, hogy egyetlen elem van ilyen, amugy exception!
            var item = db.TodoItems.Single(x =>x.Id == id);

            //Ha nem garantalhato, akkor: (ha nincs ilyen elem, akkor null-lal ter vissza. Kivetelt ez is dob, ha tobb talalat van)
            //var item = MyDb.Lista.SingleOrDefault(x => x.Id == id);

            //Ezt az elemet kell modositanunk, atadjuk az Edit.cshtml-nek
            return View(item);
        }
        
        [HttpPost]
        public ActionResult Edit(int id, string name, bool done) 
        //public ActionResult Edit(TodoItem item) // nem jon vissza adat a view-bol
        {
            //a modositott elem kikeresese
            var item = db.TodoItems.Single(x => x.Id == id);
            //A modositasok vegrehajtasa
            item.Name = name;
            item.Done = done;

            db.SaveChanges();
            return RedirectToAction("Index");            
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var item = db.TodoItems.Single(x => x.Id == id);
            return View(item);
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            var item = db.TodoItems.Single(x => x.Id == id); 
            db.TodoItems.Remove(item);
            db.SaveChanges();
            return RedirectToAction("Index");             
        }

        public ActionResult Detalis(int id)
        {
            var item = db.TodoItems.Single(x => x.Id == id);
            return View(item);

        }

        public ActionResult Teszt()
        {
            return View();
        }
    }
} 

ToDoApp/ToDoApp/Views/Todo/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@*ha nincs megadva a formon a method,
akkor alapbol GET*@
<form method="post">
    <input name="name">
    <input id="isDone" name="isDone" type="checkbox" value="true" >
    <input name="isDone" type="hidden" value="false">
    @*@Html.CheckBox("isDone")*@ @*ASP.NET MVC adja, a fenti 2 sor html kodot generalja, a bongeszoben mar az lathato*@
    <input type="submit" value="Mentés" >
    <button>Mentés</button>
</form>

@Html.ActionLink("Mégsem " , "Index")  

ToDoApp/ToDoApp/Views/Todo/Delete.cshtml
@model ToDoApp.Models.TodoItem

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Done)
        </dd>

    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Todo")) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.Id)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoApp/ToDoApp/Views/Todo/Detalis.cshtml
@model ToDoApp.Models.TodoItem

@{
    ViewBag.Title = "Detalis";
}

<h2>Detalis</h2>

<div>
    <h4>TodoItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Done)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Done)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoApp/ToDoApp/Views/Todo/Edit.cshtml
@model ToDoApp.Models.TodoItem

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "Todo", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)

    @Html.EditorFor(x => x.Name)
    @Html.EditorFor(x => x.Done)

    @*@Html.ValidationSummary(true, "", new { @class = "text-danger" })*@

    <input type="submit" value="Mentés" /> //felkuldi az urlapot [POST], utana bemegy a TodoController.cs-be
}

@Html.ActionLink("Back to List", "Index")

ToDoApp/ToDoApp/Views/Todo/Index.cshtml
@model List<ToDoApp.Models.TodoItem>

@{
    ViewBag.Title = "TodoList";
}

<h2>Bevásárlólista</h2>
@*mindeket megoldas ugyanoda visz, a masodik a beepitett ASP.NET
    szolgaltatas, nem kell megadni a Controllert, mert tudja, hol vagyunk.*@
@*Ezek a megjegyzesek nem latszanak a bongeszoben view source eseten*@
<a href="/Todo/Create">Uj cikk felvitele</a>
@Html.ActionLink("Uj cikk felvitele", "Create")

<ol>
    @foreach (var todoItem in Model)
    {
        if (todoItem.Done)
        {
            <li><strike>@Html.ActionLink(todoItem.Name, "Detalis", new { id = todoItem.Id })</strike>  @Html.ActionLink("Módosítás", "Edit", new { id = todoItem.Id })  @Html.ActionLink("Törlés", "Delete", new { id = todoItem.Id })  </li>
        }
        else
        {
            <li>@Html.ActionLink(todoItem.Name, "Detalis", new { id = todoItem.Id })   @Html.ActionLink("Módosítás", "Edit", new { id = todoItem.Id })  @Html.ActionLink("Törlés", "Delete", new { id = todoItem.Id })  </li>
        }
    }
</ol>
@*alapertelmezetten POST*@
@using (Html.BeginForm("Create", "Todo"))
{
    @Html.TextBox("Name")
    @Html.CheckBox("isDone")
    <button>Mentés</button>
}

ToDoApp/ToDoApp/Views/Todo/Teszt.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Teszt</title>
        @*A kulso allomanyt hivatkozzuk, hogy betoltse a bongeszo*@
    <link rel="stylesheet" type="text/css" href="~/Content/Sajat.css">
</head>
<body class="azureHatter">
    <div class="pirosHatter">
        <h1 class="kekHatter">Ez az oldal címe</h1>
        <div class="kekHatter">
            Ez pedig az oldalon található bármilyen szöveg
        </div>
    </div>
</body>
</html>